# Generated by Django 4.1.6 on 2023-05-03 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(help_text='Enter a food allergy (e.g. gluten)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('customer_username', models.DateField(blank=True, null=True)),
                ('customer_password', models.CharField(max_length=30)),
                ('customer_first', models.CharField(max_length=100)),
                ('customer_last', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('employee_first', models.CharField(max_length=100)),
                ('employee_last', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_city', models.CharField(max_length=100)),
                ('employee_state', models.CharField(max_length=100)),
                ('employee_zipcode', models.CharField(default='68134', max_length=5, verbose_name='zip code')),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_phone', models.CharField(max_length=12)),
                ('employee_DOB', models.DateField(blank=True, null=True)),
                ('employee_wage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('menu_item_name', models.CharField(max_length=100)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu_item_description', models.CharField(max_length=100)),
                ('menu_item_ingredients', models.CharField(max_length=100)),
                ('menu_item_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('menu_is_a_Drink', models.BooleanField(default=True, help_text='Check if this is item is a drink, uncheck if it is a snack')),
                ('allergen', models.ManyToManyField(help_text='Select a food allergy', to='tearoom.allergen')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=100)),
                ('restaurant_city', models.CharField(max_length=100)),
                ('restaurant_state', models.CharField(max_length=100)),
                ('restaurant_zipcode', models.CharField(default='68134', max_length=5, verbose_name='zip code')),
                ('restaurant_email', models.EmailField(max_length=254)),
                ('restaurant_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('review_title', models.CharField(default='Enter a review title', max_length=100)),
                ('review_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(default='Comment on your experience', max_length=4000)),
                ('menu_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tearoom.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this restaurant', primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_time', models.CharField(max_length=100)),
                ('order_address', models.CharField(max_length=100)),
                ('order_phone', models.CharField(default=4029999999, max_length=12)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tearoom.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tearoom.employee')),
                ('menuItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tearoom.menuitem')),
            ],
        ),
    ]
